{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "314652cb-eccf-4c8d-a4a2-1f5b877a3e9b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import ttkbootstrap as ttk\n",
    "from ttkbootstrap.constants import*\n",
    "\n",
    "app = ttk.Window(title=\"My Themed App\", themename=\"darkly\",size=(400,300))\n",
    "\n",
    "label = ttk.Label(app, text=\"Hello , ttkbootstrap!\",font=(\"Helvetica\",16))\n",
    "label.pack(pady=20)\n",
    "\n",
    "button = ttk.Button(app,text=\"Click Me\", bootstyle=SUCCESS)\n",
    "button.pack()\n",
    "\n",
    "app.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a1072f12-af71-4334-9151-c470d768769a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import ttkbootstrap as ttk\n",
    "from ttkbootstrap.constants import *\n",
    "\n",
    "app = ttk.Window(\"Form Demo\", themename=\"flatly\",size=(400, 250))\n",
    "\n",
    "label=ttk.Label(app, text=\"Username:\").pack(pady=5)\n",
    "username=ttk.Entry(app)\n",
    "username.pack(pady=5)\n",
    "\n",
    "ttk.Label(app, text=\"Gender:\").pack()\n",
    "gender=ttk.Combobox(app, values=[\"Male\",\"Female\",\"Other\"])\n",
    "gender.pack(pady=5)\n",
    "\n",
    "ttk.Button(app, text=\"Submit\", bootstyle=PRIMARY).pack(pady=10)\n",
    "\n",
    "app.mainloop()\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9bc20518-77eb-48df-bfe9-6af212fe4539",
   "metadata": {},
   "outputs": [],
   "source": [
    "import ttkbootstrap as ttk \n",
    "from ttkbootstrap.constants import * \n",
    "\n",
    "q=[\"Q1.Grand Central Terminal, Park Avenue, New York is the world's\",\n",
    "   \"Q2. Entomology is the science that studies\",\n",
    "   \"Q3.Eritrea, which became the 182nd member of the UN in 1993, is in the continent of\",\n",
    "   \"Q4. Garampani sanctuary is located at\",\n",
    "   \"Q5. For which of the following disciplines is Nobel Prize awarded?\"]\n",
    "\n",
    "qopt = [[\"A. largest railway station\",\"B. highest railway station\",\n",
    "         \"C. longest railway station\",\"D. None of the above\"],\n",
    "       [\"A. Behavior of human beings\",\"B. Insects\",\"C.  The origin and history of technical and scientific terms\",\n",
    "        \"D. The formation of rocks\"],\n",
    "       [\"A. Asia\",\"B. Africa\",\"C. Europe\",\"Australia\"],\n",
    "       [\"A. Junagarh, Gujarat\",\"B. Diphu, Assam\",\"C. Kohima, Nagaland\",\"D. Gangtok, Sikkim\"],\n",
    "       [\"A. Physics and Chemistry\",\"B. Physiology or Medicine\",\n",
    "        \"C. Literature, Peace and Economics\",\"D.  All of the above\"]]\n",
    "\n",
    "qans =[0,1,1,1,3]\n",
    "uans=\"\"\n",
    "marks=0\n",
    "cnt=0\n",
    "\n",
    "def showQ():\n",
    "    qlabel.config(text=q[cnt])\n",
    "    r0.config(text=qopt[cnt][0])\n",
    "    r1.config(text=qopt[cnt][1])\n",
    "    r2.config(text=qopt[cnt][2])\n",
    "    r3.config(text=qopt[cnt][3])\n",
    "\n",
    "def result():\n",
    "    global marks\n",
    "    if var1.get()==qans[cnt]:\n",
    "        marks+=1\n",
    "        result1.set(f\"correct ans:{marks} out of 5\")\n",
    "\n",
    "def buttonclick():\n",
    "    global cnt\n",
    "    if button.cget(\"text\")==\"Next\":\n",
    "        if cnt<3:\n",
    "            result()\n",
    "            cnt+=1\n",
    "            showQ()\n",
    "        else:\n",
    "            result()\n",
    "            cnt+=1\n",
    "            showQ()\n",
    "            button.config(text=\"Finish\")\n",
    "    else:\n",
    "         result()\n",
    "            \n",
    "def cancelclick():\n",
    "    pass\n",
    "\n",
    "\n",
    "root = ttk.Window(themename=\"cyborg\")\n",
    "root.geometry(\"500x350\")\n",
    "root.title(\"Quiz\")\n",
    "\n",
    "qlabel = ttk.Label(root, text=\"Q\",font=(\"Helvetica\", 16))\n",
    "qlabel.pack(pady=(40,10)) \n",
    "\n",
    "var1 = ttk.IntVar() \n",
    "r0 = ttk.Radiobutton(root,bootstyle=\"primary\",text=\"opt1\",value=0,variable=var1)\n",
    "r1 = ttk.Radiobutton(root,bootstyle=\"primary\",text=\"opt2\",value=1,variable=var1)\n",
    "r2 = ttk.Radiobutton(root,bootstyle=\"primary\",text=\"opt3\",value=2,variable=var1)\n",
    "r3 = ttk.Radiobutton(root,bootstyle=\"primary\",text=\"opt4\",value=3,variable=var1)\n",
    "\n",
    "r0.pack()\n",
    "r1.pack()\n",
    "r2.pack()\n",
    "r3.pack()\n",
    "\n",
    "button = ttk.Button(root,text=\"Next\",bootstyle=\"success\",command=buttonclick)\n",
    "button.pack(pady=20)\n",
    "\n",
    "button1 = ttk.Button(root,text=\"Cancel\",bootstyle=\"success\",command=cancelclick)\n",
    "button1.pack(pady=20)\n",
    "\n",
    "result1 = ttk.StringVar()\n",
    "result_label = ttk.Label(font=(\"Courier New\",18),textvariable=result1)\n",
    "result_label.pack(pady=(40,100))\n",
    "\n",
    "showQ()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ae589b4-5a98-4384-9d41-9ed9ae3f38fb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
